[package]
name = "ops"
version = "0.1.0"
authors = ["Szymon Wieloch <szymon.wieloch@gmail.com>"]

[dependencies]
opslib = { path = "opslib" }
clap = "2.26.0"
log = "0.3.8"
ipnetwork = "0.12.6"

[workspace]
members = ["opslib"]

#[features]
#ipv6-methods = ["ipnetwork/ipv6-methods"]
